# Generated by Django 3.0.8 on 2020-07-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('class_room', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('weixin_group', models.CharField(max_length=20, null=True)),
                ('student_gender', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('student_type', models.CharField(max_length=50, null=True)),
                ('student_phone', models.CharField(max_length=50, null=True)),
                ('student_email', models.CharField(max_length=100, null=True)),
                ('delivery_name', models.CharField(max_length=100, null=True)),
                ('delivery_phone', models.CharField(max_length=100, null=True)),
                ('delivery_address_cn', models.CharField(max_length=200, null=True)),
                ('delivery_address_en', models.CharField(max_length=200, null=True)),
                ('delivery_zipcode', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'student_address',
            },
        ),
    ]
