# Generated by Django 3.0.8 on 2020-07-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='student_address',
        ),
    ]
